### ISSUE TITLE
Fix CLI doc URL indexing in Algolia

### ISSUE THREAD

**Issue by alanchrt** [smallstep/docs#120]
It ended up being a time sink to try to get full paths to CLI reference docs in Algolia search results. We should follow up and fix the hack/workarond.

https://github.com/smallstep/docs/blob/9fe75ea72361a9f2374fe4080a7e5f76c4ef345d/src/components/Search/search-result.jsx#L50-L54

**Comment by tashian** [comment]
No longer using Algolia so I'll close this one
