### ISSUE TITLE
If `step-ssh` is closed-source, clarify that it is

### ISSUE THREAD

**Issue by nodakai** [smallstep/docs#159]
https://smallstep.com/docs/ssh/hosts-step-by-step#step-3-install-the-step-ssh-utilities

We have to think twice, thrice before plugging a binary blob into our core infrastructure (we don't even have its GPG signature)

**Comment by tashian** [comment]
Hello Kai, thanks for the note. We're sending you an email response for this issue, and we will be updating the docs soon on this.

**Comment by nodakai** [comment]
You shouldn't have closed this ticket "as completed" when you are only planning to update the docs "soon".

If you actually want to avoid mentioning it as a closed-source software, you could have just say so and closed this ticket as "not planned"

**Comment by tashian** [comment]
Hi Kai, thanks for the ping on this.

By closing this I'm not implying that we have made a decision about it either way. What you've raised here is more than a simple yes/no decision about what we say on a docs page. The bigger issue we face is one of trust and safety. As a small security startup, we have an long-term challenge of meeting people's need for trust and safety with our software. This is super important, ongoing work for us, and along the way we'll continue to share how we are navigating the relationship between our paid/open core product, and our open source work.
