### ISSUE TITLE
Misleading provisioners documentation

### ISSUE THREAD

**Issue by IamLunchbox** [smallstep/docs#171]
If you look at https://smallstep.com/docs/step-ca/provisioners, the part `options*: see the [options](https://smallstep.com/docs/step-ca/provisioners/#options) section for more details.` in the acme-section seems to imply, that there is an anchor object at `#options`, which provides more information, Since this anchor does not exist, I assume, that this is residue content from refactoring this documentation section.
  
I propose, that these references should be rephrased and point towards the given example configuration above, e.g. "see the example configuration".

**Comment by tashian** [comment]
This has been addressed, thank you.
