### ISSUE TITLE
Document ability to configure PostgreSQL via Environment variables

### ISSUE THREAD

**Issue by kudiyarov** [smallstep/docs#188]
Please add to [Postgresql DB configuration](https://smallstep.com/docs/step-ca/configuration/#postgresql) information about possibility of configuring Postgres DSN via ENV variables supported by underlay pgx go package.

Take a look at https://github.com/smallstep/certificates/issues/1256 for details.

**Comment by jbperrin88** [comment]
Hello @kudiyarov 

I was in the same situtation and i use External Secret Operator ;)

https://external-secrets.io/v0.8.3/guides/templating/

without inject but with existing secret . It's working like a charm
