### ISSUE TITLE
Document template time functions

### ISSUE THREAD

**Issue by tashian** [smallstep/docs#334]
https://github.com/smallstep/crypto/pull/539

**Comment by maraino** [comment]
All the functions but `toTimeLayout` can be implemented using pure sprig, but they are more complicated:
* Formatting a Unix Epoch to something that can be unmarshalled to a time.Time with UTC:
```go
{{ formatTime .unixEphoch }}
{{ dateInZone "2006-01-02T15:04:05Z07:00" .float64 "UTC" }}
```
* Parse a time.Time marshalled as JSON:
```go
{{ parseTime .notBefore }}
{{ toDate "2006-01-02T15:04:05Z07:00" .notAfter }}
```
