### ISSUE TITLE
Nebula provisioner docs

### ISSUE THREAD

**Issue by maraino** [smallstep/docs#94]
### Description

The provisioner docs at https://smallstep.com/docs/step-ca/provisioners do not include docs for the nebula provisioner.

The nebula provisioner SANs or principals are always validated against the nebula certificate name and/or IPs, and it cannot issue SSH-user certificates.

**Comment by hslatman** [comment]
See https://github.com/smallstep/docs/pull/48

**Comment by maraino** [comment]
Duplicated
