### ISSUE TITLE
Consider move from MDX to Markdoc

### ISSUE THREAD

**Issue by tashian** [smallstep/docs#98]
[markdoc/markdoc
](https://github.com/markdoc/markdoc)

Some benefits:

- overall better syntax (no {``}, supports markdown inside component blocks eg. within the body of a tag)
- header ID annotations
- auto table of contents
- stripe is actively adding features (search is coming soon :D :D)
- sounds like the renderer is faster than MDX
- If most of the work here would involve converting a bunch of search and replace, I may be willing to shave those yaks.

Once there's a good search function, it could really make this worth the effort

**Comment by PatrickHeneise** [comment]
You can use custom header ids with [remark-heading-id](https://github.com/imcuttle/remark-heading-id) and the Table of Contents can be extracted using [marked.lexer()](https://github.com/opstrace/next-product-docs/blob/main/src/serialize.js#L102).

Markdoc looks more like a template language for MD, it'll be difficult to read / render those outside the "docs" (ie. locally or on GitHub).
